version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "uv"
    directory: "/cloud-run-service/app"
    schedule:
      interval: "weekly"
  - package-ecosystem: "uv"
    directory: "/cloud-run-service/job"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/env/dev"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/cloud-run-service/app"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/cloud-run-service/job"
    schedule:
      interval: "weekly"
